apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-blob-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: "uniquevol"
    volumeAttributes:
      containerName: testblobaks  # Name of your Azure Blob container
      storageAccount: aeraaks  # Your Azure Storage Account name
    nodeStageSecretRef:
      name: azure-blob-secret  # Reference to the secret created earlier
      namespace: default
