apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-blob-pvc  # Ensure this matches what your pod is referencing
spec:
  accessModes:
    - ReadWriteMany  # This must match the access mode of your PersistentVolume (PV)
  resources:
    requests:
      storage: 10Gi  # This should be less than or equal to the PV's capacity
